=== Aitanaasecas/ApuntesDAM/Linguaxes de Marcas e Sistemas de Xestión de Información/Ejercicios/3. XML/bsg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="banco">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="abreviatura" type="xs:string"/>
                <xs:element name="presidente">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellidos" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fundación">
                    <xs:complexType>
                        <xs:attribute name="dia" type="xs:gDay"/>
                        <xs:attribute name="mes" type="xs:gMonth"/>
                        <xs:attribute name="año" type="xs:gYear"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sucursal" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="superficie">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="area" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="unidad" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="empleados">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="clave" type="xs:string"/>
                                        <xs:element name="empleado" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="NSS">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:length value="12"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="nombre" type="xs:string" maxOccurs="1"/>
                                                    <xs:element name="apellidos" type="xs:string" maxOccurs="1"/>
                                                    <xs:element name="cargo" nillable="true">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Director"/>
                                                                <xs:enumeration value="Interventor"/>
                                                                <xs:enumeration value="Otros"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:maxLength value="6"/>
                                                            <xs:pattern value="E[AEIOU]([3-6]{2}||[9])([a-z]{2,3})"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id_banco" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>    
</xs:schema>

=== Aitanaasecas/ApuntesDAM/Linguaxes de Marcas e Sistemas de Xestión de Información/Ejercicios/3. XML/BancoSimpáticoGallego.xml
<?xml version="1.0" encoding="UTF-8"?>
<banco id_banco="4444" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bsg.xsd">

	<nombre>Banco Simpático Gallego</nombre>
	<abreviatura>BSG</abreviatura>
	<presidente>
		<nombre>Víctor Manuel</nombre>
		<apellidos>Rodríguez Caamaño</apellidos>
	</presidente>
	<fundación dia="---20" mes="--10--" año="1892"></fundación>
	<sucursal id="1234">
		<superficie unidad="m2">
			<area>540</area>
		</superficie>
		<empleados>
			<clave>empleados1234</clave>
			<empleado id="EA9ab">
				<NSS>586875283456</NSS>
				<nombre>Carlos</nombre>
				<apellidos>González Muiño</apellidos>
				<cargo>Director</cargo>
			</empleado>
			<empleado id="EA9ab">
				<NSS>119457314331</NSS>
				<nombre>Ramón</nombre>
				<apellidos>Castiñeiras Blanco</apellidos>
				<cargo>Interventor</cargo>
			</empleado>
			<empleado id="EA9ab">
				<NSS>120045673321</NSS>
				<nombre>Cristina</nombre>
				<apellidos>Fernández Pensado</apellidos>
				<cargo>Otros</cargo>
			</empleado>
		</empleados>
	</sucursal>
	<sucursal id="5678">
		<superficie unidad="m2">
			<area>620</area>
		</superficie>
		<empleados>
			<clave>empleados5678</clave>
		<empleado id="EA9ab">
			<NSS>983728173652</NSS>
			<nombre>Tamara</nombre>
			<apellidos>Blanco Álvarez</apellidos>
			<cargo>Director</cargo>
		</empleado>
		<empleado id="EA9ab">
			<NSS>029375469182</NSS>
			<nombre>Cristian</nombre>
			<apellidos>Pazos Abelenda</apellidos>
			<cargo>Interventor</cargo>
		</empleado>
		<empleado id="EA9ab">
			<NSS>334460098001</NSS>
			<nombre>Maria</nombre>
			<apellidos>Mouro Antelo</apellidos>
			<cargo>Otros</cargo>
		</empleado>
		</empleados>
	</sucursal>
</banco>
